project_id = "hcdovzqggbqxkzfkzxbk"

[functions.get-technician-emails]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.public-reset-password]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.classify-batteries-bulk]
verify_jwt = false