-- Create reports table matching Excel export structure
CREATE TABLE public.reports (
  -- Identification
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_date TEXT NOT NULL,
  created_time TEXT NOT NULL,
  technician_name TEXT,
  site_code TEXT NOT NULL,
  state_uf TEXT,
  total_cabinets INTEGER NOT NULL DEFAULT 1,
  
  -- Site general info
  panoramic_photo_url TEXT,
  
  -- Cabinet 1
  gab1_tipo TEXT,
  gab1_protecao TEXT,
  gab1_tecnologias_acesso TEXT,
  gab1_tecnologias_transporte TEXT,
  gab1_fcc_fabricante TEXT,
  gab1_fcc_tensao TEXT,
  gab1_fcc_gerenciado TEXT,
  gab1_fcc_gerenciavel TEXT,
  gab1_fcc_consumo TEXT,
  gab1_fcc_qtd_ur TEXT,
  gab1_bat1_tipo TEXT,
  gab1_bat1_fabricante TEXT,
  gab1_bat1_capacidade TEXT,
  gab1_bat1_data_fabricacao TEXT,
  gab1_bat1_estado TEXT,
  gab1_bat2_tipo TEXT,
  gab1_bat2_fabricante TEXT,
  gab1_bat2_capacidade TEXT,
  gab1_bat2_data_fabricacao TEXT,
  gab1_bat2_estado TEXT,
  gab1_bat3_tipo TEXT,
  gab1_bat3_fabricante TEXT,
  gab1_bat3_capacidade TEXT,
  gab1_bat3_data_fabricacao TEXT,
  gab1_bat3_estado TEXT,
  gab1_bat4_tipo TEXT,
  gab1_bat4_fabricante TEXT,
  gab1_bat4_capacidade TEXT,
  gab1_bat4_data_fabricacao TEXT,
  gab1_bat4_estado TEXT,
  gab1_bat5_tipo TEXT,
  gab1_bat5_fabricante TEXT,
  gab1_bat5_capacidade TEXT,
  gab1_bat5_data_fabricacao TEXT,
  gab1_bat5_estado TEXT,
  gab1_bat6_tipo TEXT,
  gab1_bat6_fabricante TEXT,
  gab1_bat6_capacidade TEXT,
  gab1_bat6_data_fabricacao TEXT,
  gab1_bat6_estado TEXT,
  gab1_bancos_interligados TEXT,
  gab1_climatizacao_tipo TEXT,
  gab1_ventiladores_status TEXT,
  gab1_ac1_modelo TEXT,
  gab1_ac1_status TEXT,
  gab1_ac2_modelo TEXT,
  gab1_ac2_status TEXT,
  gab1_ac3_modelo TEXT,
  gab1_ac3_status TEXT,
  gab1_ac4_modelo TEXT,
  gab1_ac4_status TEXT,
  gab1_plc_status TEXT,
  gab1_alarme_status TEXT,
  gab1_foto_transmissao TEXT,
  gab1_foto_acesso TEXT,
  
  -- Cabinet 2
  gab2_tipo TEXT,
  gab2_protecao TEXT,
  gab2_tecnologias_acesso TEXT,
  gab2_tecnologias_transporte TEXT,
  gab2_fcc_fabricante TEXT,
  gab2_fcc_tensao TEXT,
  gab2_fcc_gerenciado TEXT,
  gab2_fcc_gerenciavel TEXT,
  gab2_fcc_consumo TEXT,
  gab2_fcc_qtd_ur TEXT,
  gab2_bat1_tipo TEXT,
  gab2_bat1_fabricante TEXT,
  gab2_bat1_capacidade TEXT,
  gab2_bat1_data_fabricacao TEXT,
  gab2_bat1_estado TEXT,
  gab2_bat2_tipo TEXT,
  gab2_bat2_fabricante TEXT,
  gab2_bat2_capacidade TEXT,
  gab2_bat2_data_fabricacao TEXT,
  gab2_bat2_estado TEXT,
  gab2_bat3_tipo TEXT,
  gab2_bat3_fabricante TEXT,
  gab2_bat3_capacidade TEXT,
  gab2_bat3_data_fabricacao TEXT,
  gab2_bat3_estado TEXT,
  gab2_bat4_tipo TEXT,
  gab2_bat4_fabricante TEXT,
  gab2_bat4_capacidade TEXT,
  gab2_bat4_data_fabricacao TEXT,
  gab2_bat4_estado TEXT,
  gab2_bat5_tipo TEXT,
  gab2_bat5_fabricante TEXT,
  gab2_bat5_capacidade TEXT,
  gab2_bat5_data_fabricacao TEXT,
  gab2_bat5_estado TEXT,
  gab2_bat6_tipo TEXT,
  gab2_bat6_fabricante TEXT,
  gab2_bat6_capacidade TEXT,
  gab2_bat6_data_fabricacao TEXT,
  gab2_bat6_estado TEXT,
  gab2_bancos_interligados TEXT,
  gab2_climatizacao_tipo TEXT,
  gab2_ventiladores_status TEXT,
  gab2_ac1_modelo TEXT,
  gab2_ac1_status TEXT,
  gab2_ac2_modelo TEXT,
  gab2_ac2_status TEXT,
  gab2_ac3_modelo TEXT,
  gab2_ac3_status TEXT,
  gab2_ac4_modelo TEXT,
  gab2_ac4_status TEXT,
  gab2_plc_status TEXT,
  gab2_alarme_status TEXT,
  gab2_foto_transmissao TEXT,
  gab2_foto_acesso TEXT,
  
  -- Cabinet 3
  gab3_tipo TEXT,
  gab3_protecao TEXT,
  gab3_tecnologias_acesso TEXT,
  gab3_tecnologias_transporte TEXT,
  gab3_fcc_fabricante TEXT,
  gab3_fcc_tensao TEXT,
  gab3_fcc_gerenciado TEXT,
  gab3_fcc_gerenciavel TEXT,
  gab3_fcc_consumo TEXT,
  gab3_fcc_qtd_ur TEXT,
  gab3_bat1_tipo TEXT,
  gab3_bat1_fabricante TEXT,
  gab3_bat1_capacidade TEXT,
  gab3_bat1_data_fabricacao TEXT,
  gab3_bat1_estado TEXT,
  gab3_bat2_tipo TEXT,
  gab3_bat2_fabricante TEXT,
  gab3_bat2_capacidade TEXT,
  gab3_bat2_data_fabricacao TEXT,
  gab3_bat2_estado TEXT,
  gab3_bat3_tipo TEXT,
  gab3_bat3_fabricante TEXT,
  gab3_bat3_capacidade TEXT,
  gab3_bat3_data_fabricacao TEXT,
  gab3_bat3_estado TEXT,
  gab3_bat4_tipo TEXT,
  gab3_bat4_fabricante TEXT,
  gab3_bat4_capacidade TEXT,
  gab3_bat4_data_fabricacao TEXT,
  gab3_bat4_estado TEXT,
  gab3_bat5_tipo TEXT,
  gab3_bat5_fabricante TEXT,
  gab3_bat5_capacidade TEXT,
  gab3_bat5_data_fabricacao TEXT,
  gab3_bat5_estado TEXT,
  gab3_bat6_tipo TEXT,
  gab3_bat6_fabricante TEXT,
  gab3_bat6_capacidade TEXT,
  gab3_bat6_data_fabricacao TEXT,
  gab3_bat6_estado TEXT,
  gab3_bancos_interligados TEXT,
  gab3_climatizacao_tipo TEXT,
  gab3_ventiladores_status TEXT,
  gab3_ac1_modelo TEXT,
  gab3_ac1_status TEXT,
  gab3_ac2_modelo TEXT,
  gab3_ac2_status TEXT,
  gab3_ac3_modelo TEXT,
  gab3_ac3_status TEXT,
  gab3_ac4_modelo TEXT,
  gab3_ac4_status TEXT,
  gab3_plc_status TEXT,
  gab3_alarme_status TEXT,
  gab3_foto_transmissao TEXT,
  gab3_foto_acesso TEXT,
  
  -- Cabinet 4
  gab4_tipo TEXT,
  gab4_protecao TEXT,
  gab4_tecnologias_acesso TEXT,
  gab4_tecnologias_transporte TEXT,
  gab4_fcc_fabricante TEXT,
  gab4_fcc_tensao TEXT,
  gab4_fcc_gerenciado TEXT,
  gab4_fcc_gerenciavel TEXT,
  gab4_fcc_consumo TEXT,
  gab4_fcc_qtd_ur TEXT,
  gab4_bat1_tipo TEXT,
  gab4_bat1_fabricante TEXT,
  gab4_bat1_capacidade TEXT,
  gab4_bat1_data_fabricacao TEXT,
  gab4_bat1_estado TEXT,
  gab4_bat2_tipo TEXT,
  gab4_bat2_fabricante TEXT,
  gab4_bat2_capacidade TEXT,
  gab4_bat2_data_fabricacao TEXT,
  gab4_bat2_estado TEXT,
  gab4_bat3_tipo TEXT,
  gab4_bat3_fabricante TEXT,
  gab4_bat3_capacidade TEXT,
  gab4_bat3_data_fabricacao TEXT,
  gab4_bat3_estado TEXT,
  gab4_bat4_tipo TEXT,
  gab4_bat4_fabricante TEXT,
  gab4_bat4_capacidade TEXT,
  gab4_bat4_data_fabricacao TEXT,
  gab4_bat4_estado TEXT,
  gab4_bat5_tipo TEXT,
  gab4_bat5_fabricante TEXT,
  gab4_bat5_capacidade TEXT,
  gab4_bat5_data_fabricacao TEXT,
  gab4_bat5_estado TEXT,
  gab4_bat6_tipo TEXT,
  gab4_bat6_fabricante TEXT,
  gab4_bat6_capacidade TEXT,
  gab4_bat6_data_fabricacao TEXT,
  gab4_bat6_estado TEXT,
  gab4_bancos_interligados TEXT,
  gab4_climatizacao_tipo TEXT,
  gab4_ventiladores_status TEXT,
  gab4_ac1_modelo TEXT,
  gab4_ac1_status TEXT,
  gab4_ac2_modelo TEXT,
  gab4_ac2_status TEXT,
  gab4_ac3_modelo TEXT,
  gab4_ac3_status TEXT,
  gab4_ac4_modelo TEXT,
  gab4_ac4_status TEXT,
  gab4_plc_status TEXT,
  gab4_alarme_status TEXT,
  gab4_foto_transmissao TEXT,
  gab4_foto_acesso TEXT,
  
  -- Cabinet 5
  gab5_tipo TEXT,
  gab5_protecao TEXT,
  gab5_tecnologias_acesso TEXT,
  gab5_tecnologias_transporte TEXT,
  gab5_fcc_fabricante TEXT,
  gab5_fcc_tensao TEXT,
  gab5_fcc_gerenciado TEXT,
  gab5_fcc_gerenciavel TEXT,
  gab5_fcc_consumo TEXT,
  gab5_fcc_qtd_ur TEXT,
  gab5_bat1_tipo TEXT,
  gab5_bat1_fabricante TEXT,
  gab5_bat1_capacidade TEXT,
  gab5_bat1_data_fabricacao TEXT,
  gab5_bat1_estado TEXT,
  gab5_bat2_tipo TEXT,
  gab5_bat2_fabricante TEXT,
  gab5_bat2_capacidade TEXT,
  gab5_bat2_data_fabricacao TEXT,
  gab5_bat2_estado TEXT,
  gab5_bat3_tipo TEXT,
  gab5_bat3_fabricante TEXT,
  gab5_bat3_capacidade TEXT,
  gab5_bat3_data_fabricacao TEXT,
  gab5_bat3_estado TEXT,
  gab5_bat4_tipo TEXT,
  gab5_bat4_fabricante TEXT,
  gab5_bat4_capacidade TEXT,
  gab5_bat4_data_fabricacao TEXT,
  gab5_bat4_estado TEXT,
  gab5_bat5_tipo TEXT,
  gab5_bat5_fabricante TEXT,
  gab5_bat5_capacidade TEXT,
  gab5_bat5_data_fabricacao TEXT,
  gab5_bat5_estado TEXT,
  gab5_bat6_tipo TEXT,
  gab5_bat6_fabricante TEXT,
  gab5_bat6_capacidade TEXT,
  gab5_bat6_data_fabricacao TEXT,
  gab5_bat6_estado TEXT,
  gab5_bancos_interligados TEXT,
  gab5_climatizacao_tipo TEXT,
  gab5_ventiladores_status TEXT,
  gab5_ac1_modelo TEXT,
  gab5_ac1_status TEXT,
  gab5_ac2_modelo TEXT,
  gab5_ac2_status TEXT,
  gab5_ac3_modelo TEXT,
  gab5_ac3_status TEXT,
  gab5_ac4_modelo TEXT,
  gab5_ac4_status TEXT,
  gab5_plc_status TEXT,
  gab5_alarme_status TEXT,
  gab5_foto_transmissao TEXT,
  gab5_foto_acesso TEXT,
  
  -- Cabinet 6
  gab6_tipo TEXT,
  gab6_protecao TEXT,
  gab6_tecnologias_acesso TEXT,
  gab6_tecnologias_transporte TEXT,
  gab6_fcc_fabricante TEXT,
  gab6_fcc_tensao TEXT,
  gab6_fcc_gerenciado TEXT,
  gab6_fcc_gerenciavel TEXT,
  gab6_fcc_consumo TEXT,
  gab6_fcc_qtd_ur TEXT,
  gab6_bat1_tipo TEXT,
  gab6_bat1_fabricante TEXT,
  gab6_bat1_capacidade TEXT,
  gab6_bat1_data_fabricacao TEXT,
  gab6_bat1_estado TEXT,
  gab6_bat2_tipo TEXT,
  gab6_bat2_fabricante TEXT,
  gab6_bat2_capacidade TEXT,
  gab6_bat2_data_fabricacao TEXT,
  gab6_bat2_estado TEXT,
  gab6_bat3_tipo TEXT,
  gab6_bat3_fabricante TEXT,
  gab6_bat3_capacidade TEXT,
  gab6_bat3_data_fabricacao TEXT,
  gab6_bat3_estado TEXT,
  gab6_bat4_tipo TEXT,
  gab6_bat4_fabricante TEXT,
  gab6_bat4_capacidade TEXT,
  gab6_bat4_data_fabricacao TEXT,
  gab6_bat4_estado TEXT,
  gab6_bat5_tipo TEXT,
  gab6_bat5_fabricante TEXT,
  gab6_bat5_capacidade TEXT,
  gab6_bat5_data_fabricacao TEXT,
  gab6_bat5_estado TEXT,
  gab6_bat6_tipo TEXT,
  gab6_bat6_fabricante TEXT,
  gab6_bat6_capacidade TEXT,
  gab6_bat6_data_fabricacao TEXT,
  gab6_bat6_estado TEXT,
  gab6_bancos_interligados TEXT,
  gab6_climatizacao_tipo TEXT,
  gab6_ventiladores_status TEXT,
  gab6_ac1_modelo TEXT,
  gab6_ac1_status TEXT,
  gab6_ac2_modelo TEXT,
  gab6_ac2_status TEXT,
  gab6_ac3_modelo TEXT,
  gab6_ac3_status TEXT,
  gab6_ac4_modelo TEXT,
  gab6_ac4_status TEXT,
  gab6_plc_status TEXT,
  gab6_alarme_status TEXT,
  gab6_foto_transmissao TEXT,
  gab6_foto_acesso TEXT,
  
  -- Cabinet 7
  gab7_tipo TEXT,
  gab7_protecao TEXT,
  gab7_tecnologias_acesso TEXT,
  gab7_tecnologias_transporte TEXT,
  gab7_fcc_fabricante TEXT,
  gab7_fcc_tensao TEXT,
  gab7_fcc_gerenciado TEXT,
  gab7_fcc_gerenciavel TEXT,
  gab7_fcc_consumo TEXT,
  gab7_fcc_qtd_ur TEXT,
  gab7_bat1_tipo TEXT,
  gab7_bat1_fabricante TEXT,
  gab7_bat1_capacidade TEXT,
  gab7_bat1_data_fabricacao TEXT,
  gab7_bat1_estado TEXT,
  gab7_bat2_tipo TEXT,
  gab7_bat2_fabricante TEXT,
  gab7_bat2_capacidade TEXT,
  gab7_bat2_data_fabricacao TEXT,
  gab7_bat2_estado TEXT,
  gab7_bat3_tipo TEXT,
  gab7_bat3_fabricante TEXT,
  gab7_bat3_capacidade TEXT,
  gab7_bat3_data_fabricacao TEXT,
  gab7_bat3_estado TEXT,
  gab7_bat4_tipo TEXT,
  gab7_bat4_fabricante TEXT,
  gab7_bat4_capacidade TEXT,
  gab7_bat4_data_fabricacao TEXT,
  gab7_bat4_estado TEXT,
  gab7_bat5_tipo TEXT,
  gab7_bat5_fabricante TEXT,
  gab7_bat5_capacidade TEXT,
  gab7_bat5_data_fabricacao TEXT,
  gab7_bat5_estado TEXT,
  gab7_bat6_tipo TEXT,
  gab7_bat6_fabricante TEXT,
  gab7_bat6_capacidade TEXT,
  gab7_bat6_data_fabricacao TEXT,
  gab7_bat6_estado TEXT,
  gab7_bancos_interligados TEXT,
  gab7_climatizacao_tipo TEXT,
  gab7_ventiladores_status TEXT,
  gab7_ac1_modelo TEXT,
  gab7_ac1_status TEXT,
  gab7_ac2_modelo TEXT,
  gab7_ac2_status TEXT,
  gab7_ac3_modelo TEXT,
  gab7_ac3_status TEXT,
  gab7_ac4_modelo TEXT,
  gab7_ac4_status TEXT,
  gab7_plc_status TEXT,
  gab7_alarme_status TEXT,
  gab7_foto_transmissao TEXT,
  gab7_foto_acesso TEXT,
  
  -- GMG and Tower
  gmg_existe TEXT,
  gmg_fabricante TEXT,
  gmg_potencia TEXT,
  gmg_combustivel TEXT,
  gmg_ultimo_teste TEXT,
  torre_ninhos TEXT,
  torre_protecao_fibra TEXT,
  torre_aterramento TEXT,
  torre_housekeeping TEXT,
  
  -- Observations
  observacoes TEXT,
  observacao_foto_url TEXT,
  
  -- Export metadata
  pdf_file_path TEXT,
  excel_file_path TEXT,
  email_sent BOOLEAN DEFAULT false,
  email_sent_at TIMESTAMP WITH TIME ZONE
);

-- Enable Row Level Security (public access for now since no auth)
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Allow public insert and select for reports
CREATE POLICY "Allow public insert" ON public.reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select" ON public.reports FOR SELECT USING (true);
CREATE POLICY "Allow public update" ON public.reports FOR UPDATE USING (true);

-- Create index for common queries
CREATE INDEX idx_reports_site_code ON public.reports(site_code);
CREATE INDEX idx_reports_state_uf ON public.reports(state_uf);
CREATE INDEX idx_reports_created_at ON public.reports(created_at DESC);