-- Add fiber optics columns to reports table
ALTER TABLE public.reports
ADD COLUMN IF NOT EXISTS fibra_qtd_abordagens integer DEFAULT 1,
ADD COLUMN IF NOT EXISTS fibra_abord1_tipo text,
ADD COLUMN IF NOT EXISTS fibra_abord1_descricao text,
ADD COLUMN IF NOT EXISTS fibra_abord2_tipo text,
ADD COLUMN IF NOT EXISTS fibra_abord2_descricao text,
ADD COLUMN IF NOT EXISTS fibra_caixas_passagem_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_caixas_subterraneas_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_subidas_laterais_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_dgos_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_dgos_ok_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_dgos_nok_qtd integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS fibra_dgo1_id text,
ADD COLUMN IF NOT EXISTS fibra_dgo1_capacidade text,
ADD COLUMN IF NOT EXISTS fibra_dgo1_cordoes text,
ADD COLUMN IF NOT EXISTS fibra_dgo2_id text,
ADD COLUMN IF NOT EXISTS fibra_dgo2_capacidade text,
ADD COLUMN IF NOT EXISTS fibra_dgo2_cordoes text,
ADD COLUMN IF NOT EXISTS fibra_dgo3_id text,
ADD COLUMN IF NOT EXISTS fibra_dgo3_capacidade text,
ADD COLUMN IF NOT EXISTS fibra_dgo3_cordoes text,
ADD COLUMN IF NOT EXISTS fibra_dgo4_id text,
ADD COLUMN IF NOT EXISTS fibra_dgo4_capacidade text,
ADD COLUMN IF NOT EXISTS fibra_dgo4_cordoes text;